--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrXMaster/TeaSpoon
branches:
- master
- work-around
projects:
  TeaSpoon:
    path: ""
    fullGzip: 9
    compressBuilds: false
...
